export const ActionTypes = {
    SET_PDF: 'SET_PDF',
    SET_PAGE: 'SET_PAGE',
    SET_SCALE: 'SET_SCALE',
    SET_VIEW_MODE: 'SET_VIEW_MODE',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_CURRENT_RESULT: 'SET_CURRENT_RESULT',
    SET_SEARCHING: 'SET_SEARCHING',
    TOGGLE_SEARCH: 'TOGGLE_SEARCH',
    SET_LOADING: 'SET_LOADING',
    RESET: 'RESET',
};
